V3
shakacode/react_on_rails-test-new-redux-generation pull request #5
Opened 2016-11-04 17:59 UTC by nostophilia

2016-11-04 18:22 UTC, nostophilia commented on client/app/bundles/HelloWorld/actions/helloWorldActionCreators.jsx
> +export default updateName;
Here if I wrote the following code, the linter would warn that I should use `export default` instead
```JavaScript
export const updateName = (text) => ({
  type: actionTypes.HELLO_WORLD_NAME_UPDATE,
  text,
});
```

2016-11-04 19:03 UTC, nostophilia commented on client/app/bundles/HelloWorld/actions/helloWorldActionCreators.jsx
> +});
Linter will warn that I should use `export default` here as there's only one action. But if I did so, mapDisptachToProps related code in the container file (HelloWorld.jsx) would be weird. Can I create a dummy action here to bypass this warning?

2016-11-06 07:55 UTC, justin808 requested changes
@nostophilia Please make the following changes and create a v4 branch. We're close!

@robwise, @alexfedoseev please confirm my suggestions.

2016-11-06 07:55 UTC, justin808 commented on client/app/bundles/HelloWorld/actions/helloWorldActionCreators.jsx
> +});
Add this line to the top of the file:

```
/* eslint-disable import/prefer-default-export */
```

2016-11-06 07:55 UTC, justin808 commented on client/app/bundles/HelloWorld/constants/helloWorldConstants.jsx
> +import mirrorCreator from 'mirror-creator';
remove `mirrorCreator`

Instead, use the simple form: 

```
export default {
  HELLO_WORLD_NAME_UPDATE: 'HELLO_WORLD_NAME_UPDATE'
};
```

So this file just has above lines..

@alexfedoseev Please confirm

2016-11-06 07:55 UTC, justin808 commented on client/app/bundles/HelloWorld/reducers/name.jsx
> +import actionTypes from '../constants/helloWorldConstants';
this file should be `helloWorldReducer.js` and not `name.jsx`

2016-11-06 07:55 UTC, justin808 commented on client/app/bundles/HelloWorld/reducers/name.jsx
> +const name = (state = '', action) => {
Let's use this for the initial state:
```
{ 
  name: ''
}
```

It's really confusing for me with a single value for the reducer.

Also, we can use the spread operator for the reducer

```
return { ...state, name: text }
```
to ensure we don't mutate state.

@robwise, @alexfedoseev please confirm

2016-11-06 07:55 UTC, justin808 commented on client/app/bundles/HelloWorld/reducers/name.jsx
> +export default name;
`export default helloWorldReducer;`

2016-11-07 05:22 UTC, alexfedoseev commented on client/app/bundles/HelloWorld/constants/helloWorldConstants.jsx
> +import mirrorCreator from 'mirror-creator';
I'd use

```js
export const HELLO_WORLD_NAME_UPDATE = 'HELLO_WORLD_NAME_UPDATE';
```

2016-11-07 05:23 UTC, alexfedoseev commented on client/app/bundles/HelloWorld/reducers/name.jsx
> +const name = (state = '', action) => {
👍

2016-11-07 21:14 UTC, robwise commented on client/app/bundles/HelloWorld/constants/helloWorldConstants.jsx
> +import mirrorCreator from 'mirror-creator';
Agree with Alex

2016-11-07 21:15 UTC, robwise commented on client/app/bundles/HelloWorld/reducers/name.jsx
> +const name = (state = '', action) => {
It's standard practice to write reducers with single values like that and is in the basic `Todos` example from Redux

2016-11-09 15:59 UTC, mongjong59 commented on client/app/bundles/HelloWorld/reducers/name.jsx
> +const name = (state = '', action) => {
Yeah. Because combineReducers is used in index.js, so the intialState is actually:

```
{ 
  name: ''
}
```

I think it's better to use combineReducers and child reducer to handle a simple slice of state. So I suggest have a name reducer in helloWorldReducer.js and also call combineReducers in this file.

2017-03-04 07:47 UTC, closed without merging